### PR TITLE
[RHCLOUD-20042] - Make type asserts safe and fortify testing

### PR DESCRIPTION
**Pull request by adamrdrew**
This patch adds a layer of safety to type asserts by wrapping all of them in functions that check for values, handle errors, provide defaults, and communicate success/failure. Full test coverage is added for the new safe assert API. Additionally new tests to check for various possible failure cases due to malformed resources are added.

### CODE REVIEW

**Comment by psav** [comment]
I've been mulling this one over for a few days. I think the thing I wasn't overly happy with was the frequent ignoring of what is essentially an error state. The bool value for if it was found or not feels really like an error. I think I would be happier with it being more of a clobberError, alwaysGiveDefault kinda deal that was exclusively used in the cases where you don't care about it not existing. In the places that we do care about if the key/item was actually found, we should just treat it as we normally do. The fact that we only use this more special case for this function leads me to believe that we should not try to make this function do too much. Thoughts?

**Comment by adamrdrew** [comment]
I can see where you are coming from. It is sort of a philosophical "depends on how you look at it thing." A key we're looking for not being there is an error from the perspective of of the observer who is invested in the business logic. We expect key A to be there, key A is not there, therefore we are in an error state. But, there's another way to look at it. From the perspective of the program code a key not being present is totally valid. It is fine to look for something in a map and not see it. That's not really an error. 

The code takes the stance of handling asserts and keys not being present via sane defaults / empty values and returning a bool as a semaphore to communicate what happened, and allows the code consuming the new code to be conditional on that and implement whatever business logic it wants. The code tries to take an Occam's Razor approach to solving the problem we observed - it does as little as possible with as little as possible.

So I'd have to toss the ball back to you and let you make the decision based on seniority. I think the implementation is sound and solves the problem we were trying to solve. If you say "No, please re-implement it to return errors, allow for a clobber error flag, and let the outside provide defaults." I will happily do that, but if you ask my opinion I think the implementation as submitted is  economical and general purpose.

But my opinion the new code aside it does leave the question open: should we be throwing errors in the resource checking code that a consumer of the code (clowder, other operators) could handle if a structure is malformed? I don't have a good answer for that. My gut feeling is no, because the goal of the consumer is to check status. If we can't find what we need to check status then status is bad. The consumers of this code and the purpose of the code is not to tell consumers why a resource is bad, just whether stuff is good or not. That said, since we're discussing stuff I think its maybe worth considering that for the future.

**Comment by adamrdrew** [comment]
Get rid of underscores.

**Comment by adamrdrew** [comment]
So I was wrong:

```
[12:37] adamdrew @ adamwork: ~/Development/rhc-osdk-utils [RHCLOUD-20042]: Up-to-date
$ make test
go fmt ./...
go vet ./...
# github.com/RedHatInsights/rhc-osdk-utils/resources
vet: resources/resources.go:196:18: cannot initialize 1 variables with 2 values
make: *** [Makefile:20: vet] Error 2
```

kind of blows my mind that go doesn't eat its own dogfood and you can do both:

```
bobo := jomo["yoyo"]
bobo, ok := jomo["yoyo"]
```

But yelling at the cloud will do no good.

**Comment by psav** [comment]
Given this - what do we want to do here?

**Comment by adamrdrew** [comment]
I vote for leaving the underscores in. It is ugly in the consuming code, but its idiomatic and logically/conceptually sound. 

An important point I forgot to bring up is that even if our prod code doesn't use the status bool in most cases, our tests do. We test for positive and negative results from every method in safe asserts. I'd hate to lose that test coverage,

**Review by psav — APPROVED** [review]

**Comment by psav** [comment]
Sign commits pls

**Pull request closed without merging**
